[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "design-patterns"
version = "0.1.0"
description = "Design patterns for a POS system"
authors = [{name="Elberth Cabrales"}]
dependencies = []
